;;; init-compat.el --- compiler/runtime compatibility -*- lexical-binding: t; -*-

(require 'tramp)
(require 'desktop)

;; Fortell byte-kompilatoren om pakkevariabler/-funksjoner som lastes senere.
(defvar mac-option-key-is-meta)
(defvar gptel-default-mode)
(defvar gptel-use-header-line)
(defvar gptel-system-message)
(defvar gptel-backend)
(defvar gptel-model)
(defvar reftex-plug-into-AUCTeX)
(defvar reftex-cite-format)
(defvar lsp-log-io)
(defvar lsp-headerline-breadcrumb-enable)
(defvar lsp-idle-delay)
(defvar lsp-completion-provider)
(defvar lsp-yaml-schemas)
(defvar lsp-yaml-format-enable)
(defvar lsp-yaml-key-ordering)
(defvar lsp-yaml-completion)
(defvar web-mode-markup-indent-offset)
(defvar web-mode-css-indent-offset)
(defvar web-mode-code-indent-offset)
(defvar js-indent-level)
(defvar polymode-exporter-output-file-format)
(defvar polymode-weaver-output-file-format)
(defvar ess-style)
(defvar inferior-ess-r-program)
(defvar TeX-auto-save)
(defvar TeX-parse-self)
(defvar TeX-engine)
(defvar lua-default-application)
(defvar highlight-indent-guides-method)
(defvar inferior-lisp-program)
(defvar sly-complete-symbol-function)
(defvar company-idle-delay)
(defvar company-minimum-prefix-length)
(defvar company-tooltip-align-annotations)

(declare-function exec-path-from-shell-initialize "exec-path-from-shell" ())
(declare-function exec-path-from-shell-copy-env "exec-path-from-shell" (var))
(declare-function gptel "gptel" (&optional name initial interactivep))
(declare-function gptel-send "gptel" (&optional arg))
(declare-function gptel-menu "gptel" ())
(declare-function gptel-make-anthropic "gptel" (name &rest args))
(declare-function lsp-format-buffer "lsp-mode" ())
(declare-function lsp-enable-which-key-integration "lsp-mode" (&optional all-modes))
(declare-function sly "sly" ())
(declare-function sly-connected-p "sly" ())
(declare-function rb/gptel-claude "init-ai" ())
(declare-function rb/gptel-send-region "init-ai" (beg end))

(provide 'init-compat)
;;; init-compat.el ends here
